#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Apr 03, 2024 11:55:17 PM CEST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import autosave_support

_bgcolor = 'SystemButtonFace'
_fgcolor = 'SystemWindowText'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("400x300+560+180")
        top.minsize(120, 1)
        top.maxsize(5124, 1345)
        top.resizable(1,  1)
        top.title("EasyStartUp")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

        self.Button1_1_1 = tk.Button(self.top)
        self.Button1_1_1.place(relx=0.0, rely=0.295, height=36, width=407)
        self.Button1_1_1.configure(activebackground="#d9d9d9")
        self.Button1_1_1.configure(activeforeground="black")
        self.Button1_1_1.configure(background="#000000")
        self.Button1_1_1.configure(disabledforeground="#b4b4b4")
        self.Button1_1_1.configure(font="-family {Tondu Beta} -size 24 -weight bold")
        self.Button1_1_1.configure(foreground="#fbdde0")
        self.Button1_1_1.configure(highlightcolor="SystemWindowText")
        self.Button1_1_1.configure(relief="flat")
        self.Button1_1_1.configure(text='''Herunterfahren in x Sec''')

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.0, rely=0.033, height=36, width=407)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#000000")
        self.Button1.configure(disabledforeground="#b4b4b4")
        self.Button1.configure(font="-family {Tondu Beta} -size 24 -weight bold")
        self.Button1.configure(foreground="#fbdde0")
        self.Button1.configure(highlightcolor="SystemWindowText")
        self.Button1.configure(relief="flat")
        self.Button1.configure(text='''Restart in Sec''')

        self.Button1_1 = tk.Button(self.top)
        self.Button1_1.place(relx=0.0, rely=0.164, height=36, width=407)
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(activeforeground="black")
        self.Button1_1.configure(background="#000000")
        self.Button1_1.configure(command=autosave_support.command1)
        self.Button1_1.configure(disabledforeground="#b4b4b4")
        self.Button1_1.configure(font="-family {Tondu Beta} -size 24 -weight bold")
        self.Button1_1.configure(foreground="#fbdde0")
        self.Button1_1.configure(highlightcolor="SystemWindowText")
        self.Button1_1.configure(relief="flat")
        self.Button1_1.configure(text='''Abbrechen''')

        self.menubar = tk.Menu(top, font="TkMenuFont", bg='SystemButtonFace'
                ,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Button1_1_1_1 = tk.Button(self.top)
        self.Button1_1_1_1.place(relx=0.0, rely=0.426, height=36, width=407)
        self.Button1_1_1_1.configure(activebackground="#d9d9d9")
        self.Button1_1_1_1.configure(activeforeground="black")
        self.Button1_1_1_1.configure(background="#000000")
        self.Button1_1_1_1.configure(disabledforeground="#b4b4b4")
        self.Button1_1_1_1.configure(font="-family {Tondu Beta} -size 24 -weight bold")
        self.Button1_1_1_1.configure(foreground="#fbdde0")
        self.Button1_1_1_1.configure(highlightcolor="SystemWindowText")
        self.Button1_1_1_1.configure(relief="flat")
        self.Button1_1_1_1.configure(text='''Restart in BIOS''')

def start_up():
    autosave_support.main()

if __name__ == '__main__':
    autosave_support.main()




